name: VoiceMessages
main: org.justc2t.voiceMessages.VoiceMessages
version: "1.0.0"
description: "Record short voice messages via Plasmo Voice activations and play them globally"
author: Just_c2t
api-version: "1.21"
folia-supported: true
depend:
  - PlasmoVoice
commands:
  recording:
    description: Toggle/play a recorded voice message by its ID
    usage: "/recording toggle <id>"
    permission: voicemessages.command
  voicemessage:
    description: Record/play a private message to a user.
    usage: "/voicemessage [Player | play] <ID>"
    permission: voicemessages.private
    aliases:
      - vm
permissions:
  voicemessages.command:
    default: true
  voicemessages.activation:
    default: true
  voicemessages.private:
    default: true
